[package]
name = "rmx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
termion = "2.0.1"
[lib]
name = "rmx_lib"
path = "src/lib.rs"

